name: 'ci'
description: 'Executes C# specific CI steps'
inputs:
  type:
    description: 'The type of CI step to run'
    required: true
  relay-endpoint:
    description: 'The endpoint of the relay e.g. relay.walletconnect.com'
    required: false
    default: 'wss://relay.walletconnect.com'
  project-id:
    description: 'WalletConnect project id'
    required: true

runs:
  using: "composite"
  steps:
  - name: Run tests
    if: inputs.type == 'unit-tests'
    shell: bash
    run: dotnet test --verbosity minimal --filter Category=unit
  
  - name: Run integration tests
    if: inputs.type == 'integration-tests'
    shell: bash
    env:
      RELAY_ENDPOINT: ${{ inputs.relay-endpoint }}
      PROJECT_ID: ${{ inputs.project-id }}
    run: dotnet test --verbosity minimal --filter Category=integration
