name: .NET Build & Test

on:
  push:
    branches: [ main, '2.0' ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          8.0.x

    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./

    - name: Build
      run: dotnet build --no-restore
      working-directory: ./

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: |
          **/bin/**/*.dll
          !**/Core Modules/**/bin/**/*.dll
          !**/Tests/**/bin/**/*.dll

  test:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test-type: [unit-tests, integration-tests]

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          8.0.x

    - name: Run tests
      uses: ./.github/actions/ci
      with:
        type: ${{ matrix.test-type }}
        project-id: ${{ secrets.PROJECT_ID }}