name: Release

on:
  release:
    types: [published]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            8.0.x
      
      - name: Run tests
        uses: ./.github/actions/ci
        with:
          type: 'unit-tests'
          project-id: ${{ secrets.PROJECT_ID }}

  pack:
    needs: test
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            8.0.x
      
      - name: Build Release
        run: dotnet build -c Release

      - name: Pack nugets
        run: dotnet pack -c Release --no-build --output .

      - name: Push to NuGet
        run: dotnet nuget push "*.nupkg" --api-key ${{secrets.nuget_api_key}} --source https://api.nuget.org/v3/index.json
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: |
            **/bin/**/*.dll
            !**/Tests/**/bin/**/*.dll

  dispatch:
    needs: pack
    runs-on: ubuntu-latest
    steps:
      - name: Trigger workflow in WalletConnectUnity
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.REPOSITORY_DISPATCH_PAT }}
          repository: walletconnect/walletconnectunity
          event-type: new-release
          client-payload: '{"tag_name": "${{ github.event.release.tag_name }}", "sha": "${{ github.sha }}"}'